ARG IMAGE_VERSION=latest

FROM godot-fedora:${IMAGE_VERSION}

ARG IMAGE_VERSION
ARG REPO_URL="https://github.com/nongvantinh/godot-engine-custom-builds"

LABEL "org.opencontainers.image.source"="$REPO_URL"

RUN dnf -y install --setopt=install_weak_deps=False \
      mingw32-gcc mingw32-gcc-c++ mingw32-winpthreads-static mingw64-gcc mingw64-gcc-c++ mingw64-winpthreads-static && \
    export LLVM_MINGW_VERSION=20251118 && \
    export LLVM_MINGW_NAME=llvm-mingw-${LLVM_MINGW_VERSION}-ucrt-ubuntu-22.04-x86_64 && \
    curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/${LLVM_MINGW_VERSION}/${LLVM_MINGW_NAME}.tar.xz && \
    tar xf ${LLVM_MINGW_NAME}.tar.xz && \
    rm -f ${LLVM_MINGW_NAME}.tar.xz && \
    mv -f ${LLVM_MINGW_NAME} /root/llvm-mingw

CMD /bin/bash