ARG IMAGE_VERSION=latest

FROM godot-fedora:${IMAGE_VERSION}

ARG IMAGE_VERSION
ARG REPO_URL="https://github.com/nongvantinh/godot-build-scripts"

LABEL "org.opencontainers.image.source"="$REPO_URL"

ENV EMSCRIPTEN_VERSION=4.0.20

RUN dnf -y install --setopt=install_weak_deps=False libatomic && \
    git clone --branch ${EMSCRIPTEN_VERSION} --progress https://github.com/emscripten-core/emsdk && \
    emsdk/emsdk install ${EMSCRIPTEN_VERSION} && \
    emsdk/emsdk activate ${EMSCRIPTEN_VERSION}

CMD ["/bin/bash"]