ARG IMAGE_VERSION=latest

FROM godot-fedora:${IMAGE_VERSION}

ARG IMAGE_VERSION
ARG REPO_URL="https://github.com/nongvantinh/godot-engine-custom-builds"

LABEL "org.opencontainers.image.source"="$REPO_URL"

ENV ANDROID_SDK_ROOT=/root/sdk
ENV ANDROID_NDK_VERSION=28.1.13356709
ENV ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/${ANDROID_NDK_VERSION}

RUN dnf -y install --setopt=install_weak_deps=False \
      java-21-openjdk-devel ncurses-compat-libs && \
    mkdir -p sdk && cd sdk && \
    export CMDLINETOOLS=commandlinetools-linux-13114758_latest.zip && \
    curl -LO https://dl.google.com/android/repository/${CMDLINETOOLS} && \
    unzip ${CMDLINETOOLS} && \
    rm ${CMDLINETOOLS} && \
    yes | cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --licenses && \
    cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" "ndk;${ANDROID_NDK_VERSION}" 'cmdline-tools;latest' 'build-tools;35.0.1' 'platforms;android-35' 'cmake;3.31.6'

CMD /bin/bash