ARG IMAGE_VERSION=latest
ARG REPO_URL="https://github.com/nongvantinh/godot-engine-custom-builds"

FROM godot-fedora:${IMAGE_VERSION}

LABEL "org.opencontainers.image.source"="$REPO_URL"

ENV EMSCRIPTEN_VERSION=3.1.64

RUN git clone --branch ${EMSCRIPTEN_VERSION} --progress https://github.com/emscripten-core/emsdk && \
    emsdk/emsdk install ${EMSCRIPTEN_VERSION} && \
    emsdk/emsdk activate ${EMSCRIPTEN_VERSION}

CMD ["/bin/bash"]