name: Use Pre-built Godot Containers

on:
  workflow_dispatch:  # Enables manual trigger from the GitHub UI

permissions:
  contents: read
  packages: read

jobs:
  run-builds:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup machine
        run: |
          chmod +x ./setup.sh
          sudo ./setup.sh


      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build.sh to Invoke Docker Builds
        run: |
          chmod +x ./build.sh
          ./build.sh  # Runs the build script

      - name: Prepare artifacts for release
        id: export
        run: |
          mkdir -p release
          cp -r out/* release/  # Copy output artifacts to a release directory
          echo "archive_directory=$(pwd)/release" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true
          tag: ${{ github.ref_name }}  # Use the current git tag or ref
          artifacts: ${{ env.archive_directory }}/*  # Upload all files in the release directory
