name: Create Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  get-latest-workflow-run-id:
    runs-on: ubuntu-latest
    outputs:
      workflow_run_id: ${{ steps.get-workflow-run-id.outputs.workflow_run_id }}
    steps:
      - name: Set up GitHub CLI authentication
        run: echo "GH_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV

      - name: Get latest workflow run ID
        id: get-workflow-run-id
        run: |
          latest_workflow_run_id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/nongvantinh/godot-engine-release/actions/artifacts \
            | jq -r '.artifacts[0].workflow_run.id')
          echo "Latest Workflow Run ID: $latest_workflow_run_id"

          # Write the workflow run ID to an environment file to set it as an output
          echo "workflow_run_id=$latest_workflow_run_id" >> $GITHUB_ENV
          echo "workflow_run_id=$latest_workflow_run_id" >> $GITHUB_OUTPUT

  create-release:
    needs: get-latest-workflow-run-id
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest artifact using Workflow Run ID
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          repository: nongvantinh/godot-engine-release
          run-id: ${{ needs.get-latest-workflow-run-id.outputs.workflow_run_id }}

      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true
          tag: ${{ github.ref_name }}
          artifacts: '**/*'  # Upload all files from downloaded artifacts
